# LANG
export LANG=ja_JP.UTF-8

# ビープ音鳴らさない
setopt nobeep

# 補完
autoload -U compinit
compinit

#LS_COLORSを設定しておく
autoload colors
colors

export LSCOLORS=exfxcxdxbxegedabagacad
export LS_COLORS='di=32:ln=34:so=32:pi=33:ex=31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
zstyle ':completion:*' list-colors "${LS_COLORS}"

######## PROMPT
PROMPT2='[%n]> '
SPROMPT="%{$fg[red]%}correct: %R -> %r [n/y/a/e]? %{$reset_color%}"

#PROMPT git

# color
blue_g1='%{[38;5;082m%}'
blue_g2='%{[38;5;085m%}'
blue_g3='%{[38;5;087m%}'
reset='%{[0m%}'

PROMPT="
 %{${fg[cyan]}%}%~%{${reset_color}%} ${vcs_info_msg_0_}
 %n@%m ${blue_g1}❯${blue_g2}❯${blue_g3}❯${reset} "

######## PROMPT END

# history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_dups     # ignore duplication command history list
setopt share_history        # share command history data 
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_find_no_dups
setopt hist_save_no_dups
setopt hist_beep

# fzf
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"
export FZF_DEFAULT_COMMAND='ag -g ""'
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# alias
alias ssh='ssh -A'
alias vi='nvim'

if ls --color -d . &>/dev/null 2>&1
then
    # Linux Style
    export LS_COLORS=$LS_COLORS
    alias ls='ls --color=tty'
else
    # BSD Style
	export LSCOLORS=$LSCOLORS
	alias ls='ls -G'
fi
